# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_BASE = "shekeriev/centos-stream-9"
VM_DOMAIN = ".do2.lab"

# rabbit machine
VM_RABBITMQ_LAST_OCTET = "100"
VM_RABBITMQ_HOST = "rabbit"
VM_RABBITMQ_RAM = 3072 

Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

  config.vm.define "rabbit" do |rabbit|
    rabbit.vm.box = BOX_BASE
    rabbit.vm.hostname = VM_RABBITMQ_HOST
    rabbit.vm.network "private_network", ip: "192.168.99." + VM_RABBITMQ_LAST_OCTET

    rabbit.vm.provision "shell", path: "add_hosts.sh"
    rabbit.vm.provision "shell", path: "install_python.sh"
    rabbit.vm.provision "shell", path: "install_docker.sh"
    rabbit.vm.provision "shell", path: "install_node_exporter.sh"  
    # Rabbit mq - run containers
    rabbit.vm.provision "shell", path: "run_rabbit_containers.sh"
    # Prometheus & Grafana
    rabbit.vm.provision "shell", path: "run_prometheus_and_grafana.sh" 

    rabbit.vm.synced_folder "vagrant", "/vagrant"

    rabbit.vm.provider "virtualbox" do |v|
      v.name = "rabbit"
      v.gui = false
      v.memory = VM_RABBITMQ_RAM
      v.cpus = 2
    end
  end

end
