# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # config.vm.define "docker" do |docker|
  #     docker.vm.box="shekeriev/centos-stream-9"
  #     docker.vm.hostname = "docker.do1.lab"
  #     docker.vm.network "private_network", ip: "192.168.99.100"
  #     docker.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  #     docker.vm.synced_folder "vagrant", "/vagrant"
  #     docker.vm.provision "shell", path: "docker-setup.sh"
  #     docker.vm.provision "shell", path: "init-containers.sh"
  #     docker.vm.provider :virtualbox do |vb|
  #         vb.customize ["modifyvm", :id, "--memory", "2048"]
  #   end
  # end

  config.vm.define "docker1" do |docker1|
    docker1.vm.box="shekeriev/centos-stream-9"
    docker1.vm.hostname = "docker1.do1.lab"
    docker1.vm.network "private_network", ip: "192.168.99.101"
    docker1.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
    docker1.vm.synced_folder "vagrant", "/vagrant"
    docker1.vm.provision "shell", path: "docker-setup.sh"
    docker1.vm.provision "shell", path: "init-containers.sh"
    # docker1.vm.provision "shell", path: "firewall-setup.sh"
    docker1.vm.provider :virtualbox do |vb|
        vb.customize ["modifyvm", :id, "--memory", "1536"]
    end
  end

  config.vm.define "docker2" do |docker2|
      docker2.vm.box="shekeriev/centos-stream-9"
      docker2.vm.hostname = "docker2.do1.lab"
      docker2.vm.network "private_network", ip: "192.168.99.102"
      docker2.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
      docker2.vm.synced_folder "vagrant", "/vagrant"
      docker2.vm.provision "shell", path: "docker-setup.sh"
      docker2.vm.provision "shell", path: "init-containers.sh"
      # docker2.vm.provision "shell", path: "firewall-setup.sh"
      docker2.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1536"]
      end
  end

  config.vm.define "docker3" do |docker3|
      docker3.vm.box="shekeriev/centos-stream-9"
      docker3.vm.hostname = "docker3.do1.lab"
      docker3.vm.network "private_network", ip: "192.168.99.103"
      docker3.vm.network "forwarded_port", guest: 8080, host: 8080, auto_correct: true
      docker3.vm.synced_folder "vagrant", "/vagrant"
      docker3.vm.provision "shell", path: "docker-setup.sh"
      docker3.vm.provision "shell", path: "init-containers.sh"
      # docker3.vm.provision "shell", path: "firewall-setup.sh"
      docker3.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "1536"]
      end
  end

end
