version: '3.8'
services:
  front:
    image: pesho02/m3-web:latest
    deploy:
      replicas: 3
    ports:
      - 8080:80
    volumes:
      - '${PWD}/web:/var/www/html:ro'
    networks:
      - bg-cities-net
    depends_on:
      - db
    restart: on-failure

  db:
    image: pesho02/m3-db:latest
    networks:
      - bg-cities-net
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      # MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
    # secrets:
    #   - db_root_password

# secrets:
#   db_root_password:
#     external: true

networks:
  bg-cities-net:
