# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|

	config.trigger.before [:up] do |trigger|
	  trigger.info = "Running ./create-dir.sh .."
	  trigger.run = {path: "create-dir.sh"}
	end

    config.ssh.insert_key = false

    config.vm.define "web" do |web|
		web.vm.provision :shell, path: "create-dir.sh"
		web.vm.box="shekeriev/centos-stream-9"
		web.vm.hostname = "web.do2.lab"
		web.vm.network "private_network", ip: "192.168.89.100"
		web.vm.network "forwarded_port", guest: 80, host: 8088, auto_correct: true
		web.vm.synced_folder "vagrant/web", "/vagrant"
		web.vm.provision "shell", path: "web.sh"
	end

	config.vm.define "db" do |db|
		db.vm.box="shekeriev/centos-stream-9"
		db.vm.hostname = "db.do2.lab"
		db.vm.network "private_network", ip: "192.168.89.101"
		db.vm.synced_folder "vagrant/db", "/vagrant"
		db.vm.provision "shell", path: "db.sh"
	end
	
end 
