global:
  scrape_interval: 15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  # - job_name: "rabbit"
  #   static_configs:
  #     - targets: ["192.168.99.100:9092"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["192.168.99.100:9100"]
      # - targets: ["rabbit-2:9100"]
      # - targets: ["rabbit-3:9100"]
  - job_name: "rabbitmq-server"
    static_configs:
      - targets: ["192.168.99.100:9081"]
      - targets: ["192.168.99.100:9082"]
      - targets: ["192.168.99.100:9083"]
  # - job_name: 'kafka-jmx'
  #   static_configs:
  #     - targets: ['kafka:9101']   this should be another exporter --> check PORT
  # - job_name: 'kafka_exporter'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.kafka_exporter'
  #     type: 'A'
  #     port: 9308
