global:
  resolve_timeout: 1m
  slack_api_url: '$SLACK_API_URL'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#devops-course'
    send_resolved: true
