global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['node1:9090']
      labels:
        role: main
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
 
  - job_name: 'debian'
    static_configs:
    - targets: ['node2:9100']
      labels:
        role: node
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
      - source_labels: [__name__, mountpoint]
        regex: 'node_filesystem_avail_bytes;.*'
        action: replace
        replacement: ""
        target_label: mountpoint

  - job_name: 'centos'
    static_configs:
    - targets: ['node3:9100']
      labels:
        role: node
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'go_.*'
        action: drop
      - source_labels: [__name__, mountpoint]
        regex: 'node_filesystem_avail_bytes;.*'
        action: replace
        replacement: ""
        target_label: mountpoint

  - job_name: 'application'
    file_sd_configs:
    - files:
      - 'application.json'

    relabel_configs:
      - source_labels: [role]
        regex: cont
        target_label: role
        replacement: container
