global:
  scrape_interval: 20s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['node1:9090']  
  - job_name: 'debian'
    static_configs:
    - targets: ['node2:9100']
  - job_name: 'centos'
    static_configs:
    - targets: ['node3:9100']
  - job_name: 'application'
    static_configs:
    - targets: ['node2:8081']
    - targets: ['node3:8081']

