# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false
  
    config.vm.define "ans" do |ans|
      ans.vm.box = "shekeriev/centos-stream-9"
      ans.vm.hostname = "ans.do2.lab"
      ans.vm.network "private_network", ip: "192.168.99.99"

      ans.vm.provider :virtualbox do |vb|
        vb.name="centos-11-with-ansible"
        vb.customize ["modifyvm", :id, "--memory", "2048"]
      end
      # ans.vm.synced_folder "vagrant", "/vagrant"
      ans.vm.provision "shell", path: "add_hosts.sh"
      ans.vm.provision "shell", path: "install_ansible_centos.sh" 
     
    end
  
    config.vm.define "web" do |web|
      web.vm.box = "shekeriev/centos-stream-9"
      web.vm.hostname = "web.do2.lab"
      web.vm.network "private_network", ip: "192.168.99.100"
      web.vm.synced_folder "app_web", "/vagrant"
      web.vm.network "forwarded_port", guest: 80, host: 8080

      web.vm.provider :virtualbox do |vb|
        vb.name="centos-9-with-docker"
        vb.customize ["modifyvm", :id, "--memory", "2048"]
      end

      web.vm.provision "shell", path: "add_hosts.sh"
      web.vm.provision "shell", path: "install_docker_centos.sh"
    end 
    
    config.vm.define "db" do |db|
      db.vm.box = "shekeriev/debian-11"
      db.vm.hostname = "db.do2.lab"
      db.vm.network "private_network", ip: "192.168.99.101"
      db.vm.synced_folder "app_db", "/vagrant"

      db.vm.provider :virtualbox do |vb|
        vb.name="centos-9-with-docker"
        vb.customize ["modifyvm", :id, "--memory", "2048"]
      end

      db.vm.provision "shell", path: "add_hosts.sh"
      db.vm.provision "shell", path: "install_docker_debian.sh" 
    end
    
  end
  