global:
  scrape_interval: 30s
  evaluation_interval: 30s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "kafka"
    static_configs:
      - targets: ["192.168.99.100:9092"]
  # - job_name: 'kafka-jmx'
  #   static_configs:
  #     - targets: ['kafka:9101']   this should be another exporter --> check PORT
  # - job_name: 'kafka_exporter'
  #   dns_sd_configs:
  #   - names:
  #     - 'tasks.kafka_exporter'
  #     type: 'A'
  #     port: 9308
