version: '3.8'
services:
  bg-app-front:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: m3-web
    ports:
      - 8080:80
    volumes:
      - '${PWD}/bg-app/web:/var/www/html:ro'
    networks:
      - bg-cities-net
    depends_on:
      - bg-app-db
    restart: on-failure

  bg-app-db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: m3-db
    networks:
      - bg-cities-net
    environment:
      MYSQL_ROOT_PASSWORD: 12345
networks:
  bg-cities-net:
